# Generated by Django 2.0.5 on 2018-05-15 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-update_time']},
        ),
    ]
