# Generated by Django 2.0.5 on 2018-05-18 02:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20180515_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='内容'),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='type_blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='type_blog',
            field=models.ManyToManyField(to='Blog.BlogType'),
        ),
    ]
