# Generated by Django 2.0.5 on 2018-06-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20180518_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='type_blog',
            field=models.ManyToManyField(blank=True, to='Blog.BlogType'),
        ),
    ]
