# Generated by Django 2.0.6 on 2018-07-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20180601_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ImgFile',
            field=models.ImageField(blank=True, upload_to='photo'),
        ),
    ]
